# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: David J. Sanders, MSc.
email: david@davidjsanders.com
description: >- # this means to ignore newlines until "baseurl:"
  Life-long learner and innovator with track record of delivering strategic outcomes and realizing business value 
  using collaborative, agile, and business driven approaches across retail, banking, engineering, and government 
  sectors in consulting and presales.
  Bridges gaps between business units and Information Technology by enabling clear paths to value through optimization,
  innovation, and transformation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.davidjsanders.com/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  dsandersAzure
linkedin_profile: www.linkedin.com/in/dsanders-msc

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
